/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InfoSimplesApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MeuMercadoDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MeuMercadoService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "MeuMercadoVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}