CREATE TABLE category (
  id UUID PRIMARY KEY,
  description TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL
);

CREATE TABLE nfce (
  id UUID PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  store TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  neighborhood TEXT NOT NULL,
  date TIMESTAMP NOT NULL,
  total_price NUMERIC NOT NULL,
  payment_method TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE product (
  id UUID PRIMARY KEY,
  description TEXT NOT NULL,
  ncm TEXT NOT NULL,
  price NUMERIC NOT NULL,
  qtd NUMERIC NOT NULL,
  unity TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  nfce_id UUID NOT NULL REFERENCES nfce(id) ON DELETE CASCADE,
  category_id UUID REFERENCES category(id) ON DELETE SET NULL
);
