INSERT INTO category (id, code, description, color) VALUES
  (gen_random_uuid(), '-', 'Outros', '#7f8c8d'),
  (gen_random_uuid(), '01', 'Animais vivos', '#8B4513'),
  (gen_random_uuid(), '02', 'Carnes', '#FF6B6B'),
  (gen_random_uuid(), '03', 'Peixes', '#4FC3F7'),
  (gen_random_uuid(), '04', 'Laticínios', '#FFF176'),
  (gen_random_uuid(), '0407', 'Ovos', '#FFD54F'),
  (gen_random_uuid(), '05', 'Produtos animais', '#A1887F'),
  (gen_random_uuid(), '06', 'Floricultura', '#E91E63'),
  (gen_random_uuid(), '07', 'Legumes', '#8BC34A'),
  (gen_random_uuid(), '08', 'Frutas', '#FF9800'),
  (gen_random_uuid(), '09', 'Café e especiarias', '#6D4C41'),
  (gen_random_uuid(), '10', 'Cereais', '#D4A373'),
  (gen_random_uuid(), '11', 'Moagem', '#BCAAA4'),
  (gen_random_uuid(), '12', 'Sementes e oleaginosas', '#C0CA33'),
  (gen_random_uuid(), '13', 'Resinas vegetais', '#FFB74D'),
  (gen_random_uuid(), '14', 'Plantas medicinais', '#388E3C'),
  (gen_random_uuid(), '15', 'Óleos e gorduras', '#FBC02D'),
  (gen_random_uuid(), '16', 'Preparações carne', '#EF5350'),
  (gen_random_uuid(), '17', 'Açúcares', '#F48FB1'),
  (gen_random_uuid(), '18', 'Cacau', '#5D4037'),
  (gen_random_uuid(), '19', 'Cereais', '#A1887F'),
  (gen_random_uuid(), '1902', 'Massas', '#FFCC80'),
  (gen_random_uuid(), '20', 'Preparações vegetais', '#AED581'),
  (gen_random_uuid(), '21', 'Alimentos diversos', '#90A4AE'),
  (gen_random_uuid(), '22', 'Bebidas alcoólicas', '#7B1FA2'),
  (gen_random_uuid(), '23', 'Resíduos alimentares', '#9E9D24'),
  (gen_random_uuid(), '24', 'Tabaco', '#6D4C41'),
  (gen_random_uuid(), '25', 'Minerais básicos', '#9E9E9E'),
  (gen_random_uuid(), '26', 'Minérios', '#757575'),
  (gen_random_uuid(), '27', 'Combustíveis minerais', '#424242'),
  (gen_random_uuid(), '28', 'Químicos inorgânicos', '#00BCD4'),
  (gen_random_uuid(), '29', 'Químicos orgânicos', '#26A69A'),
  (gen_random_uuid(), '30', 'Farmacêuticos', '#AB47BC'),
  (gen_random_uuid(), '31', 'Fertilizantes', '#66BB6A'),
  (gen_random_uuid(), '32', 'Tintas e pigmentos', '#EC407A'),
  (gen_random_uuid(), '33', 'Perfumaria', '#F06292'),
  (gen_random_uuid(), '34', 'Produtos limpeza', '#29B6F6'),
  (gen_random_uuid(), '35', 'Enzimas e colas', '#FF7043'),
  (gen_random_uuid(), '36', 'Explosivos', '#D32F2F'),
  (gen_random_uuid(), '37', 'Fotografia', '#7E57C2'),
  (gen_random_uuid(), '38', 'Químicos diversos', '#26C6DA'),
  (gen_random_uuid(), '39', 'Plásticos', '#FFA726'),
  (gen_random_uuid(), '40', 'Borracha', '#5C6BC0'),
  (gen_random_uuid(), '41', 'Couros', '#8D6E63'),
  (gen_random_uuid(), '42', 'Bolsas e malas', '#BA68C8'),
  (gen_random_uuid(), '43', 'Peles', '#A1887F'),
  (gen_random_uuid(), '44', 'Madeira', '#8B5E3C'),
  (gen_random_uuid(), '45', 'Cortiça', '#D7CCC8'),
  (gen_random_uuid(), '46', 'Cestaria', '#A1887F'),
  (gen_random_uuid(), '47', 'Papel reciclado', '#BDBDBD'),
  (gen_random_uuid(), '48', 'Papel e cartão', '#E0E0E0'),
  (gen_random_uuid(), '49', 'Publicações', '#9FA8DA'),
  (gen_random_uuid(), '50', 'Seda', '#FFF9C4'),
  (gen_random_uuid(), '51', 'Lã', '#A1887F'),
  (gen_random_uuid(), '52', 'Algodão', '#FFFFFF'),
  (gen_random_uuid(), '53', 'Fibras vegetais', '#DCEDC8'),
  (gen_random_uuid(), '54', 'Filamentos sintéticos', '#B2EBF2'),
  (gen_random_uuid(), '55', 'Fibras sintéticas', '#80DEEA'),
  (gen_random_uuid(), '56', 'Tecidos especiais', '#CE93D8'),
  (gen_random_uuid(), '57', 'Tapetes', '#6D4C41'),
  (gen_random_uuid(), '58', 'Tecidos decorativos', '#FFCDD2'),
  (gen_random_uuid(), '59', 'Tecidos técnicos', '#B0BEC5'),
  (gen_random_uuid(), '60', 'Malhas', '#FFE082'),
  (gen_random_uuid(), '61', 'Vestuário malha', '#F48FB1'),
  (gen_random_uuid(), '62', 'Vestuário', '#E57373'),
  (gen_random_uuid(), '63', 'Artigos têxteis', '#F5F5F5'),
  (gen_random_uuid(), '64', 'Calçados', '#795548'),
  (gen_random_uuid(), '65', 'Chapéus', '#D4E157'),
  (gen_random_uuid(), '66', 'Guarda-chuvas', '#64B5F6'),
  (gen_random_uuid(), '67', 'Penas e cabelo', '#FFB300'),
  (gen_random_uuid(), '68', 'Pedra e gesso', '#BCAAA4'),
  (gen_random_uuid(), '69', 'Cerâmica', '#FFAB91'),
  (gen_random_uuid(), '70', 'Vidro', '#81D4FA'),
  (gen_random_uuid(), '71', 'Metais preciosos', '#FFD700'),
  (gen_random_uuid(), '72', 'Ferro e aço', '#9E9E9E'),
  (gen_random_uuid(), '73', 'Metais trabalhados', '#B0BEC5'),
  (gen_random_uuid(), '74', 'Cobre', '#B87333'),
  (gen_random_uuid(), '75', 'Níquel', '#B0BEC5'),
  (gen_random_uuid(), '76', 'Alumínio', '#CFD8DC'),
  (gen_random_uuid(), '78', 'Chumbo', '#607D8B'),
  (gen_random_uuid(), '79', 'Zinco', '#90A4AE'),
  (gen_random_uuid(), '80', 'Estanho', '#BDBDBD'),
  (gen_random_uuid(), '81', 'Metais comuns', '#757575'),
  (gen_random_uuid(), '82', 'Ferramentas', '#546E7A'),
  (gen_random_uuid(), '83', 'Metais diversos', '#9E9E9E'),
  (gen_random_uuid(), '84', 'Máquinas mecânicas', '#FF7043'),
  (gen_random_uuid(), '85', 'Máquinas elétricas', '#42A5F5'),
  (gen_random_uuid(), '86', 'Trilhos e veículos', '#78909C'),
  (gen_random_uuid(), '87', 'Veículos automóveis', '#1E88E5'),
  (gen_random_uuid(), '88', 'Aeronaves', '#3949AB'),
  (gen_random_uuid(), '89', 'Embarcações', '#0288D1'),
  (gen_random_uuid(), '90', 'Instrumentos ópticos', '#8E24AA'),
  (gen_random_uuid(), '91', 'Relógios', '#FDD835'),
  (gen_random_uuid(), '92', 'Instrumentos musicais', '#7CB342'),
  (gen_random_uuid(), '93', 'Armas', '#D32F2F'),
  (gen_random_uuid(), '94', 'Móveis', '#A1887F'),
  (gen_random_uuid(), '95', 'Brinquedos', '#FF4081'),
  (gen_random_uuid(), '96', 'Diversos', '#9E9E9E'),
  (gen_random_uuid(), '97', 'Arte e coleção', '#6A1B9A')
ON CONFLICT (code) DO NOTHING;