import { v7 as uuidv7 } from "uuid";
import { db } from ".";
import { category } from "./schema";

const categories = [
  { code: "-", description: "Outros", color: "#7f8c8d" },
  { code: "01", description: "Animais vivos", color: "#8B4513" },
  { code: "02", description: "Carnes", color: "#FF6B6B" },
  { code: "03", description: "Peixes", color: "#4FC3F7" },
  { code: "04", description: "Laticínios", color: "#FFF176" },
  { code: "0407", description: "Ovos", color: "#FFD54F" },
  { code: "05", description: "Produtos animais", color: "#A1887F" },
  { code: "06", description: "Floricultura", color: "#E91E63" },
  { code: "07", description: "Legumes", color: "#8BC34A" },
  { code: "08", description: "Frutas", color: "#FF9800" },
  { code: "09", description: "Café e especiarias", color: "#6D4C41" },
  { code: "10", description: "Cereais", color: "#D4A373" },
  { code: "11", description: "Moagem", color: "#BCAAA4" },
  { code: "12", description: "Sementes e oleaginosas", color: "#C0CA33" },
  { code: "13", description: "Resinas vegetais", color: "#FFB74D" },
  { code: "14", description: "Plantas medicinais", color: "#388E3C" },
  { code: "15", description: "Óleos e gorduras", color: "#FBC02D" },
  { code: "16", description: "Preparações carne", color: "#EF5350" },
  { code: "17", description: "Açúcares", color: "#F48FB1" },
  { code: "18", description: "Cacau", color: "#5D4037" },
  { code: "19", description: "Cereais", color: "#A1887F" },
  { code: "1902", description: "Massas", color: "#FFCC80" },
  { code: "20", description: "Preparações vegetais", color: "#AED581" },
  { code: "21", description: "Alimentos diversos", color: "#90A4AE" },
  { code: "22", description: "Bebidas alcoólicas", color: "#7B1FA2" },
  { code: "23", description: "Resíduos alimentares", color: "#9E9D24" },
  { code: "24", description: "Tabaco", color: "#6D4C41" },
  { code: "25", description: "Minerais básicos", color: "#9E9E9E" },
  { code: "26", description: "Minérios", color: "#757575" },
  { code: "27", description: "Combustíveis minerais", color: "#424242" },
  { code: "28", description: "Químicos inorgânicos", color: "#00BCD4" },
  { code: "29", description: "Químicos orgânicos", color: "#26A69A" },
  { code: "30", description: "Farmacêuticos", color: "#AB47BC" },
  { code: "31", description: "Fertilizantes", color: "#66BB6A" },
  { code: "32", description: "Tintas e pigmentos", color: "#EC407A" },
  { code: "33", description: "Perfumaria", color: "#F06292" },
  { code: "34", description: "Produtos limpeza", color: "#29B6F6" },
  { code: "35", description: "Enzimas e colas", color: "#FF7043" },
  { code: "36", description: "Explosivos", color: "#D32F2F" },
  { code: "37", description: "Fotografia", color: "#7E57C2" },
  { code: "38", description: "Químicos diversos", color: "#26C6DA" },
  { code: "39", description: "Plásticos", color: "#FFA726" },
  { code: "40", description: "Borracha", color: "#5C6BC0" },
  { code: "41", description: "Couros", color: "#8D6E63" },
  { code: "42", description: "Bolsas e malas", color: "#BA68C8" },
  { code: "43", description: "Peles", color: "#A1887F" },
  { code: "44", description: "Madeira", color: "#8B5E3C" },
  { code: "45", description: "Cortiça", color: "#D7CCC8" },
  { code: "46", description: "Cestaria", color: "#A1887F" },
  { code: "47", description: "Papel reciclado", color: "#BDBDBD" },
  { code: "48", description: "Papel e cartão", color: "#E0E0E0" },
  { code: "49", description: "Publicações", color: "#9FA8DA" },
  { code: "50", description: "Seda", color: "#FFF9C4" },
  { code: "51", description: "Lã", color: "#A1887F" },
  { code: "52", description: "Algodão", color: "#FFFFFF" },
  { code: "53", description: "Fibras vegetais", color: "#DCEDC8" },
  { code: "54", description: "Filamentos sintéticos", color: "#B2EBF2" },
  { code: "55", description: "Fibras sintéticas", color: "#80DEEA" },
  { code: "56", description: "Tecidos especiais", color: "#CE93D8" },
  { code: "57", description: "Tapetes", color: "#6D4C41" },
  { code: "58", description: "Tecidos decorativos", color: "#FFCDD2" },
  { code: "59", description: "Tecidos técnicos", color: "#B0BEC5" },
  { code: "60", description: "Malhas", color: "#FFE082" },
  { code: "61", description: "Vestuário malha", color: "#F48FB1" },
  { code: "62", description: "Vestuário", color: "#E57373" },
  { code: "63", description: "Artigos têxteis", color: "#F5F5F5" },
  { code: "64", description: "Calçados", color: "#795548" },
  { code: "65", description: "Chapéus", color: "#D4E157" },
  { code: "66", description: "Guarda-chuvas", color: "#64B5F6" },
  { code: "67", description: "Penas e cabelo", color: "#FFB300" },
  { code: "68", description: "Pedra e gesso", color: "#BCAAA4" },
  { code: "69", description: "Cerâmica", color: "#FFAB91" },
  { code: "70", description: "Vidro", color: "#81D4FA" },
  { code: "71", description: "Metais preciosos", color: "#FFD700" },
  { code: "72", description: "Ferro e aço", color: "#9E9E9E" },
  { code: "73", description: "Metais trabalhados", color: "#B0BEC5" },
  { code: "74", description: "Cobre", color: "#B87333" },
  { code: "75", description: "Níquel", color: "#B0BEC5" },
  { code: "76", description: "Alumínio", color: "#CFD8DC" },
  { code: "78", description: "Chumbo", color: "#607D8B" },
  { code: "79", description: "Zinco", color: "#90A4AE" },
  { code: "80", description: "Estanho", color: "#BDBDBD" },
  { code: "81", description: "Metais comuns", color: "#757575" },
  { code: "82", description: "Ferramentas", color: "#546E7A" },
  { code: "83", description: "Metais diversos", color: "#9E9E9E" },
  { code: "84", description: "Máquinas mecânicas", color: "#FF7043" },
  { code: "85", description: "Máquinas elétricas", color: "#42A5F5" },
  { code: "86", description: "Trilhos e veículos", color: "#78909C" },
  { code: "87", description: "Veículos automóveis", color: "#1E88E5" },
  { code: "88", description: "Aeronaves", color: "#3949AB" },
  { code: "89", description: "Embarcações", color: "#0288D1" },
  { code: "90", description: "Instrumentos ópticos", color: "#8E24AA" },
  { code: "91", description: "Relógios", color: "#FDD835" },
  { code: "92", description: "Instrumentos musicais", color: "#7CB342" },
  { code: "93", description: "Armas", color: "#D32F2F" },
  { code: "94", description: "Móveis", color: "#A1887F" },
  { code: "95", description: "Brinquedos", color: "#FF4081" },
  { code: "96", description: "Diversos", color: "#9E9E9E" },
  { code: "97", description: "Arte e coleção", color: "#6A1B9A" },
];

async function main() {
  try {
    await db.delete(category);

    for (const categoryData of categories) {
      await db.insert(category).values({
        id: uuidv7(),
        description: categoryData.description,
        code: categoryData.code,
        color: categoryData.color,
      });
    }
  } catch (error) {
    console.error("❌ Error during seeding:", error);
    throw error;
  }
}

main().catch(console.error);